# Generated by Django 2.1 on 2018-09-25 14:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTH_BLOG', '0004_auto_20180919_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headImg',
            field=models.ImageField(null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
